# Global variable definitions for NSE (Tidyverse & ggplot2)
# Avoids 'no visible binding for global variable' notes during R CMD check

if (getRversion() >= "2.15.1") {
  utils::globalVariables(c(
    ".",
    ".data",
    ".pred",
    ".pred_risk_score",
    ".subject_id",
    ".truth",
    ".entry",
    "clean_level",
    "conf.high",
    "conf.low",
    "counts",
    "cum_pct",
    "ecdf",
    "estimate",
    "feature",
    "HR",
    "label",
    "Level",
    "log(HR)",
    "log_p",
    "log2_fold_change",
    "max_v",
    "method",
    "min_v",
    "n",
    "p.value",
    "parameter",
    "pct",
    "Role",
    "sd.error",
    "se",
    "Statistic",
    "strata",
    "term",
    "tile",
    "time",
    "Value",
    "values",
    "var",
    "Variable",
    "variable",
    "95% CI"
  ))
}
